# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ffd10435a12a8d3e299f59400109d1ddc61691e7530cce26fb7dba903b56770af5b330b928aa675016573e55d02febee342b05aa375d6531f09e1339161f578

test:
  secret_key_base: 0549894e97b969282e9ddecccd6dc2da99fadae1f7a443ec7d27822b453d50c563f4aa02de241aec798db1695d14d1e32d6c53fc432fb8503bfe56314a616c79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
